apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-postgresql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2-csi
